# Generated by Django 4.1.2 on 2022-11-11 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('detail', models.TextField()),
                ('is_color_activ', models.BooleanField(default=None)),
            ],
            options={
                'verbose_name': 'Xizmatlar',
            },
        ),
        migrations.CreateModel(
            name='CaruselDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Karusel Tavsilot',
            },
        ),
        migrations.CreateModel(
            name='CaruselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/carusel')),
            ],
            options={
                'verbose_name': 'Karusel',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Kontakt',
            },
        ),
        migrations.CreateModel(
            name='GallaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/gallary')),
            ],
            options={
                'verbose_name': 'Gallereya turlari',
            },
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('phone_number', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Buyurtma shakli',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=100)),
                ('roomprice', models.PositiveIntegerField()),
                ('servicename', models.CharField(max_length=100)),
                ('serviceprice', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Xona turlari',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Xizmat kursatish turlari',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Sozlamalar',
            },
        ),
        migrations.CreateModel(
            name='SubServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_exist', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clining.cardservices')),
            ],
            options={
                'verbose_name': 'Sub xizmatlar',
            },
        ),
        migrations.CreateModel(
            name='GallaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('gallarycategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clining.gallarycategory')),
            ],
            options={
                'verbose_name': 'Gallereya tavsilotlari',
            },
        ),
    ]
