# Generated by Django 4.1.2 on 2022-11-12 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaruselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_uz', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(upload_to='media/carusel')),
            ],
            options={
                'verbose_name': 'Karusel',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Kontakt',
            },
        ),
        migrations.CreateModel(
            name='GallaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_uz', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(upload_to='media/gallary')),
            ],
            options={
                'verbose_name': 'Gallereya turlari',
            },
        ),
        migrations.CreateModel(
            name='OrderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Buyurtma turlari',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=100)),
                ('roomprice', models.PositiveIntegerField()),
                ('servicename', models.CharField(max_length=100)),
                ('serviceprice', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Xona turlari',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('name_en', models.CharField(blank=True, max_length=120, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=120, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Xizmat kursatish turlari',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Sozlamalar',
            },
        ),
        migrations.CreateModel(
            name='SubServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('is_exist', models.BooleanField(default=True, verbose_name='is_exist')),
            ],
            options={
                'verbose_name': 'Sub Card Xizmatlar',
            },
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('ordercategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clining.ordercategory')),
            ],
            options={
                'verbose_name': 'Zakazlar',
            },
        ),
        migrations.CreateModel(
            name='GallaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('gallarycategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clining.gallarycategory')),
            ],
            options={
                'verbose_name': 'Gallereya tavsilotlari',
            },
        ),
        migrations.CreateModel(
            name='CaruselDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('caruselimage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clining.caruselimage')),
            ],
            options={
                'verbose_name': 'Karusel Tavsilot',
            },
        ),
        migrations.CreateModel(
            name='CardServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('detail', models.TextField(verbose_name='detail')),
                ('detail_en', models.TextField(null=True, verbose_name='detail')),
                ('detail_uz', models.TextField(null=True, verbose_name='detail')),
                ('detail_ru', models.TextField(null=True, verbose_name='detail')),
                ('service', models.ManyToManyField(to='clining.subservices')),
            ],
            options={
                'verbose_name': 'Card Xizmatlar',
            },
        ),
    ]
