# Generated by Django 4.1.2 on 2022-11-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clining", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="roomname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="roomname"
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="roomprice",
            field=models.IntegerField(blank=True, null=True, verbose_name="roomprice"),
        ),
        migrations.AlterField(
            model_name="orders",
            name="servicename",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="servicename"
            ),
        ),
    ]
