# Generated by Django 4.1.2 on 2022-11-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Buyurtma turlari',
            },
        ),
        migrations.RemoveField(
            model_name='orderform',
            name='description',
        ),
        migrations.AddField(
            model_name='orderform',
            name='ordercategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clining.ordercategory'),
        ),
    ]
