# Generated by Django 4.1.2 on 2022-11-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clining", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactform",
            name="description",
            field=models.TextField(
                default=0, max_length=550, verbose_name="description"
            ),
            preserve_default=False,
        ),
    ]
