# Generated by Django 4.1.2 on 2022-11-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clining", "0002_alter_orders_roomname_alter_orders_roomprice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="name",
            field=models.CharField(default=0, max_length=65, verbose_name="name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="phone_number",
            field=models.IntegerField(default=0, verbose_name="phone_number"),
            preserve_default=False,
        ),
    ]
