# Generated by Django 4.1.2 on 2022-11-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0002_ordercategory_remove_orderform_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderform',
            options={'verbose_name': 'Zakazlar'},
        ),
    ]
