# Generated by Django 4.1.3 on 2022-11-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0002_remove_servicetype_roomcategory_orders_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='roomcategory',
        ),
        migrations.AddField(
            model_name='orders',
            name='nameroom',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='nameservice',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='priceroom',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='priceservice',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
