# Generated by Django 4.1.2 on 2022-11-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0003_alter_orderform_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderform',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
