# Generated by Django 4.1.3 on 2022-11-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0004_remove_orders_priceroom_remove_orders_priceservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='priceroom',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='priceservice',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
