# Generated by Django 4.1.2 on 2022-11-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clining", "0004_alter_orders_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="name",
            field=models.CharField(default=0, max_length=65, verbose_name="name"),
            preserve_default=False,
        ),
    ]
