# Generated by Django 4.1.2 on 2022-11-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0004_alter_orderform_email_alter_orderform_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
