# Generated by Django 4.1.3 on 2022-11-10 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0005_orders_priceroom_orders_priceservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='nameroom',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='nameservice',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='priceroom',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='priceservice',
        ),
        migrations.AddField(
            model_name='orders',
            name='roomcatergory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clining.roomcategory'),
        ),
        migrations.AddField(
            model_name='orders',
            name='servicecategoriy',
            field=models.ManyToManyField(to='clining.price'),
        ),
    ]
