# Generated by Django 4.1.2 on 2022-11-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0005_contactform_description_alter_contactform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
