# Generated by Django 4.1.2 on 2022-11-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clining", "0005_alter_orders_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactform",
            name="email",
        ),
    ]
