# Generated by Django 4.1.3 on 2022-11-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0006_remove_orders_nameroom_remove_orders_nameservice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='roomcatergory',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='servicecategoriy',
        ),
        migrations.AddField(
            model_name='orders',
            name='roomname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='roomprice',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='servicename',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='serviceprice',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
