# Generated by Django 4.1.2 on 2022-11-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0006_alter_contactform_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardservices',
            options={'verbose_name': 'Card Xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='subservices',
            options={'verbose_name': 'Sub Card Xizmatlar'},
        ),
        migrations.RemoveField(
            model_name='cardservices',
            name='is_color_activ',
        ),
        migrations.RemoveField(
            model_name='subservices',
            name='service',
        ),
        migrations.AddField(
            model_name='cardservices',
            name='detail_en',
            field=models.TextField(null=True, verbose_name='detail'),
        ),
        migrations.AddField(
            model_name='cardservices',
            name='detail_ru',
            field=models.TextField(null=True, verbose_name='detail'),
        ),
        migrations.AddField(
            model_name='cardservices',
            name='detail_uz',
            field=models.TextField(null=True, verbose_name='detail'),
        ),
        migrations.AddField(
            model_name='cardservices',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='cardservices',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='cardservices',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='cardservices',
            name='service',
            field=models.ManyToManyField(to='clining.subservices'),
        ),
        migrations.AddField(
            model_name='caruseldetail',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='caruseldetail',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='caruseldetail',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='caruseldetail',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caruseldetail',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caruseldetail',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caruselimage',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='caruselimage',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='caruselimage',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gallarycategory',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gallarycategory',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gallarycategory',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gallarydetail',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gallarydetail',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gallarydetail',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gallarydetail',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gallarydetail',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gallarydetail',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='name_ru',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='name_uz',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subservices',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='subservices',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='subservices',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cardservices',
            name='detail',
            field=models.TextField(verbose_name='detail'),
        ),
        migrations.AlterField(
            model_name='cardservices',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='cardservices',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='subservices',
            name='is_exist',
            field=models.BooleanField(default=True, verbose_name='is_exist'),
        ),
        migrations.AlterField(
            model_name='subservices',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
