# Generated by Django 4.1.2 on 2022-11-15 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clining", "0006_alter_orderitem_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Total",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="orders",
            name="roomprice",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="orders",
            name="serviceprice",
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name="orders",
            name="totl",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="clining.total",
            ),
        ),
    ]
