# Generated by Django 4.1.2 on 2022-11-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clining", "0006_remove_contactform_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="projects/", verbose_name="Image"),
                ),
                ("service", models.CharField(max_length=50, verbose_name="Service")),
                ("place", models.CharField(max_length=50, verbose_name="Place")),
                ("description", models.TextField(verbose_name="Description")),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
