# Generated by Django 4.1.2 on 2022-11-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clining", "0007_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="project",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="project",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="project",
            name="place_en",
            field=models.CharField(max_length=50, null=True, verbose_name="Place"),
        ),
        migrations.AddField(
            model_name="project",
            name="place_ru",
            field=models.CharField(max_length=50, null=True, verbose_name="Place"),
        ),
        migrations.AddField(
            model_name="project",
            name="place_uz",
            field=models.CharField(max_length=50, null=True, verbose_name="Place"),
        ),
        migrations.AddField(
            model_name="project",
            name="service_en",
            field=models.CharField(max_length=50, null=True, verbose_name="Service"),
        ),
        migrations.AddField(
            model_name="project",
            name="service_ru",
            field=models.CharField(max_length=50, null=True, verbose_name="Service"),
        ),
        migrations.AddField(
            model_name="project",
            name="service_uz",
            field=models.CharField(max_length=50, null=True, verbose_name="Service"),
        ),
    ]
