# Generated by Django 4.1.2 on 2022-11-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clining", "0007_total_alter_orders_roomprice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="serviceprice",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
