# Generated by Django 4.1.2 on 2022-11-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clining", "0008_project_description_en_project_description_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_view_in_home",
            field=models.BooleanField(default=True, verbose_name="Is View In Home"),
        ),
    ]
