# Generated by Django 4.1.2 on 2022-11-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clining", "0008_alter_orders_serviceprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="serviceprice",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
