# Generated by Django 4.1.2 on 2022-11-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0009_project_is_view_in_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_view_in_home',
        ),
        migrations.RemoveField(
            model_name='project',
            name='place',
        ),
        migrations.RemoveField(
            model_name='project',
            name='place_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='place_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='place_uz',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service_uz',
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=0, max_length=200, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
