# Generated by Django 4.1.2 on 2022-11-18 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0010_alter_project_options_remove_project_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('description', models.TextField(max_length=550)),
            ],
            options={
                'verbose_name': 'Sub Project',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='gallary',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clining.subproj'),
            preserve_default=False,
        ),
    ]
