# Generated by Django 4.1.2 on 2022-11-18 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clining', '0011_subproj_project_gallary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('name_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('description', models.TextField(max_length=550, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Xona turlari',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='gallary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clining.room2'),
        ),
        migrations.DeleteModel(
            name='SubProj',
        ),
    ]
